SELECT USER
FROM DUAL;
--==> SCOTT

--○ 테이블 생성 (TBL_STUDENT)

CREATE TABLE TBL_STUDENT
( SID   NUMBER
, NAME  VARCHAR2(30)
, TEL   VARCHAR2(40)
, CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)
);
--==> Table TBL_STUDENT이(가) 생성되었습니다.

--○ 테이블 생성 (TBL_GRADE)
CREATE TABLE TBL_GRADE
( SID   NUMBER
, SUB1  NUMBER(3)
, SUB2  NUMBER(3)
, SUB3  NUMBER(3)
, CONSTRAINT GRADE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT GRADE_SID_FK FOREIGN KEY(SID)
             REFERENCES TBL_STUDENT(SID)
);
--==> Table TBL_GRADE이(가) 생성되었습니다.

--○ 시퀀스 생성 (TBL_STUDENT)
CREATE SEQUENCE SEQ_STUDENT
NOCACHE;
--==> Sequence SEQ_STUDENT이(가) 생성되었습니다.

DROP SEQUENCE SEQ_GRADE;

CREATE SEQUENCE SEQ_GRADE
NOCACHE;
--==> Sequence SEQ_GRADE이(가) 생성되었습니다.

--○ 샘플 데이터 입력 
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(SEQ_STUDENT.NEXTVAL, '한혜림', '010-1111-1111');
--==> 1 행 이(가) 삽입되었습니다.

INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(SEQ_STUDENT.NEXTVAL, '이무림', '010-2222-2222');
--==> 1 행 이(가) 삽입되었습니다.


INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(SEQ_GRADE.NEXTVAL, 100, 50, 90);
--==> 1 행 이(가) 삽입되었습니다.


INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(SEQ_GRADE.NEXTVAL, 80, 90, 70);
--==> 1 행 이(가) 삽입되었습니다.


--○ 데이터 삭제
DELETE
FROM TBL_STUDENT
WHERE SID=1;

DELETE
FROM TBL_GRADE
WHERE SID=1;


--○ 테이블 조회
SELECT SID, NAME, TEL
FROM TBL_STUDENT;

SELECT *
FROM TBL_GRADE;

--○ 뷰 생성
CREATE OR REPLACE VIEW STUDENTVIEW
AS
SELECT SID, NAME, TEL, (SELECT COUNT(*)
                        FROM TBL_GRADE) AS SUB
FROM TBL_STUDENT;
--==> View STUDENTVIEW이(가) 생성되었습니다.


CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, ROUND((TOT/3), 2) AS AVG, 
CASE WHEN( TOT/3 ) >= 60 THEN '합격'
     WHEN( TOT/3 ) < 60 THEN '불합격'
     ELSE '과락'
END GRADE
FROM
(
  SELECT G.SID,S.NAME,G.SUB1,G.SUB2,G.SUB3, (G.SUB1+G.SUB2+G.SUB3) AS TOT
  FROM TBL_GRADE G, TBL_STUDENT S
  WHERE G.SID = S.SID
 );
--==> View GRADEVIEW이(가) 생성되었습니다.


--○ 뷰 조회
SELECT SID, NAME, TEL, SUB
FROM STUDENTVIEW
ORDER BY SID;

SELECT *
FROM GRADEVIEW;


--○ 카운트
SELECT COUNT(*) AS COUNT
FROM TBL_STUDENT;

SELECT COUNT(*) AS COUNT
FROM TBL_GRADE;